
"use client";

import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { BookUser, Star, CheckCircle2 } from "lucide-react";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";


const guideSections = [
    {
        title: "1. Getting Started: Sign Up & Login",
        content: [
            {
                heading: "Sign Up",
                text: "To create a new account, click the “Enroll Now” button on our homepage or go directly to the 'Sign Up' page. You'll need to provide your name, email, and a password. Be sure to select the “Student” role."
            },
            {
                heading: "Login",
                text: "Once your account is created, you can log in anytime from the 'Login' page. After logging in, you'll be taken directly to the Student Dashboard."
            }
        ]
    },
    {
        title: "2. The Student Dashboard: Your Learning Hub",
        content: [
            "The dashboard is your mission control for all things learning. Here’s what you’ll find:",
            {
                heading: "Welcome Message",
                text: "A friendly greeting and an encouraging AI-powered message just for you!"
            },
            {
                heading: "Today's Schedule",
                text: "A quick look at the live classes scheduled for the current day."
            },
            {
                heading: "My Courses",
                text: "A colorful display of all the subjects for your class. Clicking on a subject will take you to a detailed view where you can find worksheets, quizzes, and games."
            },
            {
                heading: "My Achievements",
                text: "Track your progress! This section shows off all the cool badges you've earned from your teacher."
            }
        ]
    },
    {
        title: "3. Navigating with the Sidebar",
        content: [
            "The sidebar on the left is your main navigation tool.",
            { heading: "Dashboard", text: "Your homepage." },
            { heading: "Subjects", text: "Dive deep into your courses. This is where you'll find all your learning materials." },
            { heading: "Syllabus", text: "See the full curriculum for your class, subject by subject." },
            { heading: "Reading Buddy", text: "A fun AI tool to help you practice reading. Give it a topic, and it will write a short story for you to read aloud!" },
            { heading: "E-Library", text: "A digital library filled with fun books to explore." },
            { heading: "Calendar", text: "A full view of your schedule, highlighting all your upcoming classes." },
            { heading: "AI Progress Report", text: "View the detailed weekly reports generated by your teacher, powered by AI to give you insights into your learning journey." }
        ]
    },
    {
        title: "4. Interacting with Subjects",
        content: [
            "When you click on a subject from the 'My Courses' section, you'll find three tabs:",
            { heading: "Worksheets", text: "View and download worksheets assigned by your teacher." },
            { heading: "Quizzes", text: "Take fun, interactive quizzes to test your knowledge. Your scores are saved for your teacher to see." },
            { heading: "Games", text: "Play educational games designed specifically for your class and subject. Learning has never been this fun!" }
        ]
    }
];

export default function UserGuideView() {
  return (
    <Card>
      <CardHeader>
        <CardTitle className="flex items-center gap-2 font-headline text-2xl">
          <BookUser /> For Parents & Students
        </CardTitle>
        <CardDescription>This guide will walk you through everything from signing up to navigating the student's personal learning dashboard.</CardDescription>
      </CardHeader>
      <CardContent>
        <Accordion type="single" collapsible className="w-full" defaultValue="item-0">
            {guideSections.map((section, index) => (
                <AccordionItem key={index} value={`item-${index}`}>
                    <AccordionTrigger className="text-left font-bold text-lg">{section.title}</AccordionTrigger>
                    <AccordionContent className="text-base text-muted-foreground space-y-4">
                        {section.content.map((item, itemIndex) => {
                            if (typeof item === 'string') {
                                return <p key={itemIndex}>{item}</p>
                            }
                            return (
                                <div key={itemIndex} className="flex items-start gap-3">
                                    <CheckCircle2 className="w-5 h-5 text-green-500 mt-1 flex-shrink-0"/>
                                    <div>
                                        <p className="font-semibold text-foreground">{item.heading}</p>
                                        <p className="text-sm">{item.text}</p>
                                    </div>
                                </div>
                            )
                        })}
                    </AccordionContent>
                </AccordionItem>
            ))}
        </Accordion>
      </CardContent>
    </Card>
  );
}
