"use client";

import { useState, useEffect } from "react";
import { supabase } from '@/lib/supabase';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { BotIcon, Loader2 } from "lucide-react";
import { RocketIcon } from "@/components/icons";
import { format } from 'date-fns';

interface ProgressReport {
    id: string;
    reportContent: string;
    generatedAt: string;
}

export default function ReportView() {
  const [reports, setReports] = useState<ProgressReport[]>([]);
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    const fetchReports = async () => {
      const { data: authData } = await supabase.auth.getUser();
      const user = authData?.user;

      if (!user) {
        setIsLoading(false);
        return;
      }

      const { data, error } = await supabase
        .from('progress_reports')
        .select('*')
        .eq('student_id', user.id)
        .order('generated_at', { ascending: false });

      if (!error && data) {
        setReports(data.map((r: any) => ({
          id: r.id,
          reportContent: r.report_content || r.reportContent || '',
          generatedAt: r.generated_at || r.generatedAt,
        })));
      }
      setIsLoading(false);
    };

    fetchReports();
  }, []);


  return (
    <Card className="shadow-sm">
        <CardHeader>
          <CardTitle className="font-headline text-2xl flex items-center gap-2">
            <BotIcon /> My AI Progress Reports
          </CardTitle>
          <CardDescription>Here are the weekly progress reports generated by your teacher.</CardDescription>
        </CardHeader>
        <CardContent>
            {isLoading && (
                 <div className="flex flex-col items-center justify-center h-64 text-center text-muted-foreground">
                    <Loader2 className="w-12 h-12 mb-4 animate-spin text-primary" />
                    <p className="font-semibold">Fetching your reports...</p>
                 </div>
            )}
            {!isLoading && reports.length === 0 && (
                <div className="flex flex-col items-center justify-center h-64 text-center text-muted-foreground">
                    <RocketIcon className="w-16 h-16 mb-4 text-primary" />
                    <p className="font-semibold">No Reports Yet!</p>
                    <p className="text-sm">Your teacher hasn't generated any progress reports for you yet. Check back soon!</p>
                </div>
            )}
             {!isLoading && reports.length > 0 && (
                <Accordion type="single" collapsible className="w-full" defaultValue="item-0">
                    {reports.map((report, index) => (
                         <AccordionItem key={report.id} value={`item-${index}`}>
                            <AccordionTrigger>
                                Weekly Report - {format(new Date(report.generatedAt), 'PPP')}
                            </AccordionTrigger>
                            <AccordionContent>
                                <div className="prose prose-sm max-w-none whitespace-pre-wrap text-foreground bg-secondary/30 p-4 rounded-md">
                                    {report.reportContent}
                                </div>
                            </AccordionContent>
                        </AccordionItem>
                    ))}
                </Accordion>
             )}
        </CardContent>
    </Card>
  );
}
